# Generated by Django 3.0.7 on 2020-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='phone'),
        ),
    ]
