# Generated by Django 3.0.7 on 2021-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_constellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='import_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='import_code'),
        ),
    ]
