# Generated by Django 3.0.7 on 2020-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0004_auto_20200628_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
    ]
