# Generated by Django 3.0.7 on 2020-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
