# Generated by Django 3.0.7 on 2021-06-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('users', '0008_auto_20200908_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to='sites.Site', verbose_name='site')),
            ],
        ),
    ]
