# Generated by Django 3.0.7 on 2021-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_import_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_photo_detail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_photo_thumbbail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
