# Generated by Django 4.1.10 on 2023-07-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20210818_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="CATJoinRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField()),
                ("email", models.EmailField(max_length=254)),
                ("city_country", models.CharField(blank=True, max_length=256)),
                ("why_join", models.TextField(blank=True)),
                ("main_offer", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="photos",
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
