# Generated by Django 4.1.11 on 2023-09-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_cluster_slug_alter_taggedcluster_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="taggedcluster",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="users.cluster",
            ),
        ),
    ]
