# Generated by Django 4.1.11 on 2023-09-05 23:09

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_cluster_slug_alter_taggedcluster_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                blank=True,
                length=8,
                max_length=8,
                null=True,
                prefix="",
            ),
        ),
    ]
