# Generated by Django 4.1.11 on 2023-09-05 23:09

import shortuuid
from django.db import migrations


def generate_short_ids(apps, schema_editor):
    Profile = apps.get_model("user", "Profile")
    for prof in Profile.objects.all():
        # keep generating short ids until we find one that
        # doesn't already exist
        short_id = shortuuid.ShortUUID().random(length=8)
        while Profile.objects.filter(short_id=short_id).exists():
            short_id = shortuuid.ShortUUID().random(length=8)

        prof.short_id = short_id
        prof.save(update_fields=["short_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_profile_short_id"),
    ]

    operations = []


migrations.RunPython(generate_short_ids, reverse_code=migrations.RunPython.noop),
