# Generated by Django 4.1.11 on 2023-09-06 17:20

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_generate_shorti_ds"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="location"
            ),
        )
    ]
