# Generated by Django 4.1.11 on 2023-10-31 22:22

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_profile_location_alter_profile_short_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text="A hex code colour to use for the header background colour",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="constellation",
            name="logo",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="logos",
                verbose_name="logo",
            ),
        )
    ]
