# Generated by Django 4.1.11 on 2023-10-31 22:46

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_constellation_background_color_constellation_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="signin_via_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="constellation",
            name="signin_via_slack",
            field=models.BooleanField(default=False),
        ),
    ]
