# Generated by Django 4.1.11 on 2023-11-16 08:16

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_constellation_signin_via_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["user__name"],
                "permissions": [
                    ("set_visibility", "Can set the visibility of a profile"),
                    ("send_invite_email", "Can send profile invite emails"),
                ],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="short_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                blank=True,
                length=8,
                max_length=8,
                null=True,
                prefix="",
                unique=True,
            ),
        ),
    ]
