# Generated by Django 4.1.13 on 2023-11-19 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_profile_options_alter_profile_short_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["user__name"],
                "permissions": [
                    ("set_visibility", "Can set the visibility of a profile"),
                    ("send_invite_email", "Can send profile invite emails"),
                    (
                        "import_profiles",
                        "Can import profiles from a CSV file, or from a Firebase export JSON file",
                    ),
                ],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
