# Generated by Django 4.1.13 on 2023-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="text_color",
            field=models.CharField(
                blank=True,
                help_text="A hex code colour to use for the header text colour",
                max_length=256,
            ),
        ),
    ]
