# Generated by Django 4.1.13 on 2023-12-05 20:30

from django.db import migrations
from ..initial_perms import populate_groups


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_constellation_text_color"),
    ]

    operations = [migrations.RunPython(populate_groups)]
