# Generated by Django 4.1.13 on 2023-12-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_auto_20231205_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="favicon",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="favicons",
                verbose_name="favicon",
            ),
        ),
    ]
