# Generated by Django 4.1.13 on 2024-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_constellation_favicon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter",
        ),
        migrations.AddField(
            model_name="profile",
            name="social_1",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="social_1"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_2",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="social_2"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_3",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="social_3"
            ),
        ),
    ]
