# Generated by Django 4.1.13 on 2024-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_remove_profile_facebook_remove_profile_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="welcome_message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
