# Generated by Django 4.1.13 on 2024-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_constellation_welcome_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constellation",
            name="welcome_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
