# Generated by Django 4.1.13 on 2024-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_constellation_welcome_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="constellation",
            name="button",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="constellation",
            name="welcome_heading",
            field=models.TextField(blank=True, null=True),
        ),
    ]
