# Generated by Django 4.2.16 on 2024-10-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_options"),
        ("users", "0029_constellation_button_constellation_welcome_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetEmailContent",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="password_reset_template",
                        serialize=False,
                        to="sites.site",
                    ),
                ),
                (
                    "email_title",
                    models.TextField(
                        blank=True,
                        default="Password Reset Request for {{ constellation }}",
                        help_text="Enter the subject of the email. For the site name, use `{{ constellation }}`.",
                        null=True,
                    ),
                ),
                (
                    "email_content",
                    models.TextField(
                        blank=True,
                        default="<p>Hello {{ profile.name }},</p><p>You requested a password reset for your account on {{ constellation }}.</p><p>Click the link below to reset your password:</p><p><a href='{{ reset_link }}'>Reset Password</a></p><p>If you did not request this email, please ignore it.</p><p>Thank you!</p>",
                        help_text="Enter the body of the email. Use `{{ profile.name }}` for the user's username, `{{ reset_link }}` for the password reset link, and `{{ constellation }}` for the site name.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SendInviteEmailContent",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="email_confirm_template",
                        serialize=False,
                        to="sites.site",
                    ),
                ),
                (
                    "email_title",
                    models.TextField(
                        blank=True,
                        default="Welcome to {{ constellation }}",
                        help_text="Enter the subject of the email. For the site name, use `{{ constellation }}`.",
                        null=True,
                    ),
                ),
                (
                    "email_content",
                    models.TextField(
                        blank=True,
                        default="<p>Dear {{ profile.name }} </p><p>Welcome to {{ constellation }}.</p><p><em>(Copy goes here to mention terms of service and community guidelines)</em></p><p>If you have any problems logging in, or you have not attempted to log in, please <a href='mailto:{{ support_email_address }}'>contact support.</a></p>",
                        help_text="Enter the body of the email. Use `{{ profile.name }}` for the user's name , `{{ constellation }}` for the site name and {{ support_email_address }} for the support email adrdress.",
                    ),
                ),
            ],
        ),
    ]
